demo_responses = {
    "what is overclocking?": {
        "answer": "Overclocking is the process of pushing computer components to their limits to increase their performance (quote 1). This involves adjusting the base speed and multipliers of the computer's components to achieve higher speeds than the default settings (quote 2).",
        "quotes": [
            {
                "num": 1,
                "text": "But this is Der Bauer, a YouTuber whose life revolves around overclocking, which means pushing computer components to their limits to increase their performance.",
                "link": "https://www.youtube.com/watch?v=7UBHapunJ1g&t=1037",
                "link_text": "Lecture 8a 17:17-17:29"
            },
            {
                "num": 2,
                "text": "Instead of keeping the base speed at 100, we increased it slightly to 102.7. However, the multiplier which was capped from the factory at a maximum of 50, he managed to increase it to 74.",
                "link": "https://www.youtube.com/watch?v=7UBHapunJ1g&t=1069",
                "link_text": "Lecture 8a 17:49-18:05"
            }
        ]
    },
    "then why not always overclock the CPU?": {
        "answer": "Overclocking the CPU is not always advisable due to several reasons. One major issue is the heat generated by overclocking, which can cause the server to overheat and affect its performance (quote 1). Additionally, when the server gets too hot, it activates throttling mechanisms to prevent damage, which can slow down operations and is not optimal for performance (quote 2). Overclocking can also lead to instability and potential failure of the system, as things start to fall apart when pushed to the extreme (quote 3).",
        "quotes": [
            {
                "num": 1,
                "text": "There are several reasons why we don't want to push the server to its limit, but the main one is the heat it generates. We don't want to overload the server because it can't dissipate the heat efficiently.",
                "link": "https://www.youtube.com/watch?v=ueJOkQhj7II&t=757",
                "link_text": "Lecture 12b 12:38-12:54"
            },
            {
                "num": 2,
                "text": "When the server feels too hot, it automatically activates thermal throttling and turbo boost technology. This means that it allows itself to work faster than planned for a short time, but if it gets too hot, it says 'wait a minute, I don't want to burn myself.' This affects performance and is not optimal.",
                "link": "https://www.youtube.com/watch?v=ueJOkQhj7II&t=740",
                "link_text": "Lecture 12b 12:20-12:37"
            },
            {
                "num": 3,
                "text": "When is there a problem? There is a problem that comes to the extreme. In the most advanced servers of Intel, like we see when we do overclocking, we really start to get to the core of things, and then things start to fall apart, and even then, usually, things will stop working long before we get to the problems, such as, for example, with the separation of spec and heat.",
                "link": "https://www.youtube.com/watch?v=7ND4iDwTfBA&t=2230",
                "link_text": "Lecture 9b 37:10-37:28"
            }
        ]
    },
    "what are some ways to manage or reduce this heat? give me an example": {
        "answer": "Some ways to manage or reduce the heat generated by overclocking include using efficient cooling technologies such as fans, heat pipes, and water cooling (quote 1). Additionally, thermal throttling and turbo boost technology can help prevent overheating by automatically slowing down operations when the server gets too hot (quote 2). An example of an extreme cooling method is pouring liquid helium on the CPU, which is even colder than liquid nitrogen, to prevent the CPU from overheating and burning out (quote 3).",
        "quotes": [
            {
                "num": 1,
                "text": "Today, there are more efficient ways to cool down CPUs using technologies such as fans, heat pipes, water cooling, and other innovative solutions.",
                "link": "https://www.youtube.com/watch?v=ueJOkQhj7II&t=704",
                "link_text": "Lecture 12b 11:44-11:56"
            },
            {
                "num": 2,
                "text": "Modern servers are equipped with thermal throttling and turbo boost technology to prevent overheating. This means that if the server gets too hot, it will automatically slow down its operations.",
                "link": "https://www.youtube.com/watch?v=ueJOkQhj7II&t=716",
                "link_text": "Lecture 12b 11:56-12:10"
            },
            {
                "num": 3,
                "text": "He is pouring liquid helium on the CPU here. it's not even liquid nitrogen but liquid helium, which is even colder, so that the CPU doesn't overheat and burn out.",
                "link": "https://www.youtube.com/watch?v=7UBHapunJ1g&t=1049",
                "link_text": "Lecture 8a 17:29-17:42"
            }
        ]
    }
}